# Generated by Django 4.2.24 on 2025-09-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.PositiveIntegerField(unique=True)),
                ('patient_name', models.CharField(max_length=120)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('denied', 'Denied'), ('paid', 'Paid'), ('review', 'Under Review')], default='review', max_length=20)),
                ('insurer', models.CharField(max_length=120)),
                ('discharge_date', models.DateField()),
                ('cpt_codes', models.CharField(help_text='Comma-separated codes, e.g. 99204,82947,99406', max_length=120)),
                ('denial_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('admin', 'Admin Note'), ('system', 'System Flag')], default='admin', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='claims.claim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
